basePath: /v1
definitions:
  inventory.InventoryUnit:
    properties:
      id:
        type: string
      name:
        type: string
      stockCount:
        type: string
      stockName:
        type: string
      stockType:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server Petstore server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths:
  /dummy:
    get:
      consumes:
      - application/json
      description: descriptions here
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: object
        "400":
          description: Bad Request
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: example GET function
      tags:
      - Users
  /inven/:id:
    get:
      parameters:
      - description: inven id
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/inventory.InventoryUnit'
        "500":
          description: Internal Server Error
      summary: find single inventory
swagger: "2.0"
